import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { CiSearch } from "react-icons/ci";
import { PiShoppingCartSimple, PiList } from "react-icons/pi";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-center justify-between w-full py-8 font-primary px-10">
          <Link href="/">
            <Image width={150} height={50} className="-mt-2" src="/Logo.png" alt="No Image found" />
          </Link>
          <div className="hidden gap-12 lg:flex">
            <Link
              className="hover:text-red-500 transition-colors duration-500 cursor-pointer"
              href="/">
              Female
            </Link>
            <Link
              className="hover:text-red-500 transition-colors duration-500 cursor-pointer"
              href="/">
              Male
            </Link>
            <Link
              className="hover:text-red-500 transition-colors duration-500 cursor-pointer"
              href="/">
              Kids
            </Link>
            <Link
              className="hover:text-red-500 transition-colors ease-in-out duration-500 cursor-pointer"
              href="/">
              All Products
            </Link>
          </div>
          <div className="relative sm:block hidden">
            <CiSearch className="absolute left-0 top-0 mt-[7px] ml-2 h-4 w-4 text-gray-500" />
            <Input
              placeholder="What are you looking for ?"
              className="w-[350px] xl:w-[370px] h-[30px] pl-10"
            />
          </div>
          <div>
            <div className="lg:block hidden relative p-1 group hover:cursor-pointer overflow-hidden transition-all transform-gpu hover:scale-[1.20] duration-700">
              <div className="absolute top-0 right-0 bg-red-500 text-white rounded-full px-[4px] py-[2px] text-xs">
                10
              </div>
              <div className="bg-[#F1F1F1] rounded-full p-[10px]">
                <PiShoppingCartSimple className="text-[25px]" />
              </div>
            </div>
            <div className="lg:hidden block p-1 group hover:cursor-pointer overflow-hidden transition-all transform-gpu hover:scale-[1.20] duration-700">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <div className="rounded-full p-[10px]">
                    <PiList className="text-[25px]" />
                  </div>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="w-56 mr-12">
                  <DropdownMenuItem className="hover:cursor-pointer flex justify-between py-2"><div>Open Cart</div><div className="bg-red-500 text-white rounded-full px-[4px] py-[2px] text-xs">10</div></DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem className="hover:cursor-pointer">All Products</DropdownMenuItem>
                  <DropdownMenuItem className="hover:cursor-pointer">Male</DropdownMenuItem>
                  <DropdownMenuItem className="hover:cursor-pointer">Female</DropdownMenuItem>
                  <DropdownMenuItem className="hover:cursor-pointer">Kids</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
